# --- General Settings ---
# set -g default-terminal "screen-256color"
# set -g default-terminal "tmux-256color"
set -g default-terminal "tmux-256color"

set -ga terminal-overrides ",xterm-256color:Tc"
set -ga terminal-overrides ",tmux-256color:Tc"

set -g mouse on               # Enable mouse support
set -g mode-keys vi           # Use Vi keybindings in copy mode
set -g set-clipboard on     # Integrate with system clipboard
set-option -g renumber-windows on # Renumber windows after closing one

# --- config from tmux-sensibl ---
# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0

# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 5
# Upgrade $TERM
set -g default-terminal "screen-256color"

# --- Keybindings ---
# Change Prefix from Ctrl+b to Ctrl+a (easier to reach)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Resize panes using Prefix + H, J, K, L (Vim style)
# The -r flag makes these keys repeatable
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Split panes using Prefix + - (horizontal) and Prefix + | (vertical)
bind = split-window -h
bind - split-window -v

# Easier and faster switching between next/prev window
unbind n
bind -n C-N previous-window
unbind p
bind -n C-n next-window
unbind c
bind -n C-t new-window

bind -n C-o kill-window

# Reload config file
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"

# Use Vim-like keybindings in copy mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# --- Plugins ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator' # Navigate panes like Vim
set -g @vim_navigator_mapping_prev "C-p"  # removes the C-\ binding
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @plugin 'catppuccin/tmux' # theme
#set -g @catppuccin_flavour 'mocha'  # Choose your flavor: latte, frappe, macchiato, mocha


run '~/.tmux/plugins/tpm/tpm'
